baseURL = "https://namamishanker.github.io/"
languageCode = "en"
title = "#!bin/namami"
theme = "hugo-coder"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
publishDir= "docs"

[params]
author = "Namami Shanker"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Namami Shanker's personal website"
keywords = "blog,developer,personal"
info = ["Backend Developer", "Pythoneer", "Musician"]
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/NamamiShanker"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/namami_shanker"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/namamishanker/"

[[params.social]]
name = "YouTube"
icon = "fa fa-2x fa-youtube"
weight = 5
url = "https://www.youtube.com/channel/UCG6jTGPkBJy-DpH-LeEG8dg"

[[menu.main]]
name = "About"
weight = 1
url = "about/"
target = "_self"
rel = "alternate"
type = "text/html"

[[menu.main]]
name = "Contact"
weight = 1
url = "contact/"
target = "_self"
rel = "alternate"
type = "text/html"
